#!/usr/bin/env zsh

export PERL5LIB=lib

checks="AVV Ponttor, AC
BART San Francisco International Airport BART Station, San Francisco
BLS Bern
BVG 900003104
CFL Luxembourg, Gare Rocade
CMTA 6397
IE Dublin
KVB 900000802
mobiliteit Luxembourg, Gare Centrale
NAHSH Flensburg
NASA Wernigerode Hbf
NVV Kassel Hauptbahnhof
ÖBB Wien Meidling
RMV Mainz Hauptbahnhof
RSAG Rostock Hbf
SaarVV Saarbrücken Hbf
STV Graz
VBB S+U Jannowitzbrücke (Berlin)
VBN Diepholz
VMT Nordhausen
VOS Osnabrück Neumarkt"

echo $checks | while read service stop; do
        echo -n "${service} ... "
        if bin/hafas-m -s $service $stop > /dev/null; then
                echo OK
        fi
done

