#!/usr/bin/env zsh

export PERL5LIB=lib

checks="DB Berlin Jannowitzbrücke
NAHSH Flensburg
NASA Wernigerode Hbf
NVV Kassel Hauptbahnhof
ÖBB Wien Meidling
VBB S+U Jannowitzbrücke (Berlin)
VBN Diepholz"

echo $checks | while read service stop; do
        echo -n "${service} ... "
        if bin/hafas-m -s $service $stop > /dev/null; then
                echo OK
        fi
done

